AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A function to experiment ruby on lambda 
Resources:
  OtherLanguage:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ruby.handler
      Runtime: nodejs6.10 
      CodeUri: ./src
Outputs:
  LambdaName:
    Description: Lambda function name generated
    Value: !Ref OtherLanguage
